# Using Machine Learning to Recommend Undergraduate Majors {#slug-two}

#### Keywords {-}

yaba, daba, do

## A beginning.

It is quite ludicrous that the American education system expects a fresh high school graduate to possess enough foresight to make an accurate decision about a college major, which could dictate his or her entire career.  Estimates of the percentage of college freshmen entering undergraduate with an undeclared major range from 20 to 50 percent; even more students change their major at least once before graduating [@gordon_undecided_1995].  Taking extra time to decide on an area of study is costly and delays graduation, with only 19 percent of students in 2014 completing their bachelor's degree in four years [@lewin_most_2014].  And even deciding on and sticking with a major at the start of college does not guarantee a happy transition into the working world.  Many young professionals find themselves unhappy with their original choice of occupation: career changes and graduate schooling in subjects unrelated to undergraduate majors are ubiquitous in today's working world.  As such, it would be extremely valuable to prospective college freshmen if they had a tool to help select an area of study likely to be a good fit from the start.

## A middle.

We have enough educational and occupational data to build a good recommender system for incoming college freshmen.  Depending on a student's academic background--i.e. what classes the student exceled in or not--an algorithm can automatically select a major which minimizes the number of major changes and maximizes future occupational satisfaction.  Of these two factors, the former is easier to measure, but the latter may be much more useful.  Operationalizing career satisfaction is difficult to do, but can be done through a combination of direct surveys on industry professionals and indirect measurements on metrics like turnover rate.

Of course, a student's academic background should be the only factor in his or her decision of a major.  It is simply the easiest to turn into variables for a machine learning algorthm.  The more interesting inputs are student personalities and interests.  These are probably the more traditional factors in deciding a major that truly interests the student.  Of course, it is uninteresting to offer music performance as a major to child who enjoys playing piano.  But, consider the following theoretical path:
1. The student starts as a music performance major and finds that practicing 10+ hours a day in the hopes of making a top orchestra is unrealistic.
2. The student studies music in the form of waveforms and finds the analysis interesting enough to switch to electrical engineering.
3. The student finds a knack for the programming assignments in his labs and switches to computer science.
The above example is the exact path my roommate in college took.  While purely anecdotal, this story represents just one of nearly infinite paths of major exploration.  A machine learning algorithm can detect similar paths of change and recommend end points to students before they even think about them.

Here, I may have diverged slightly from my initial proposition.  I have changed from a recommender system for undeclared majors to an algorithm that predicts major changes in order to help short circuit the beginning and end.  In reality, we probably need a whole suite of ML algorithm in order to truly help students select majors.  It is not enough to simply build one algorithm.  We need multiple algorithms to aid students at multiple junctions in their educational and professional careers.

## An end.

One key point to make is that these algorithms are simply meant to be suggestions.  It is easy to imagine a dystopian world where people's jobs and studies are dictated to them by a computer.  Instead, we need to offer students tools so that they can make the best informed decision possible, without forcing any specific choice.  If successful, there will be huge time and financial benefits to future generations of students.